namespace: dev

configmap:
  postgres_cast:
    name: postgres-cast-configmap
    POSTGRES_USER: "cast"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "cast_db"
  
  cast_service:
    name: cast-service-config
    uri: "postgresql://cast:password@pg-cast/cast_db"
  
  postgres_movie:
    name: postgres-movie-configmap
    POSTGRES_USER: "movie"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "movie_db"
    
  movie_service:
    name: movie-service-config
    uri: "postgresql://movie:password@pg-movie:5432/movie_db"
    cast_service_uri: "http://cast:8000/api/v1/casts/"

Deployment:
  imagePullPolicy: IfNotPresent
  replicasCount: 1

  postgres:
    image: postgres:12.1-alpine
    mountPath: /var/lib/postgresql/data/
    ports: 5432
  
  cast_db:
    name: postgres-cast-db

  cast_service:
    image: superbero/cast_service:latest
    name: cast-svc-deploy

  movie_db:
    name: postgres-movie-db

  movie_service:
    image: superbero/movie_service:latest
    name: movie-svc-deploy

volumes:
  storageClassName: standard
  accessModes: ReadWriteMany
  
  persistentvolume:
    name: postgres-volumes
    size: 10Gi
    volume_path: /Users/admin/volumes
   
  persistentvolumeclaim:
    cast_size: 5Gi
    movie_size: 10Gi
    storageClassName: standard
    accessModes: ReadWriteMany

    cast_db:
      name: postgres-cast-volumes-claims
    
    movie_db:
      name: postgres-movie-volumes-claims

services:
  postgres_cast:
    name: pg-cast
    type: ClusterIP
    port: 5432
    targetPort: 5432

  cast_service:
    type: ClusterIP
    name: cast-db-service
    port: 8000
    targetPort: 8000

  postgres_movie:
    name: pg-movie
    type: ClusterIP
    ports:  5432
    targetPort: 5432
    protocol: TCP

  movie_service:
    type: ClusterIP
    name: movie-service
    port: 8000
    targetPort: 8000
    protocol: TCP
   
  
    
    

  

