namespace: dev

configmap:
  postgres_cast:
    name: postgres-cast-configmap
    POSTGRES_USER: "cast"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "cast_db"
  
  cast_service:
    name: cast-service-config
    uri: "postgresql://cast:password@pg-cast/cast_db"

Deployment:
  imagePullPolicy: IfNotPresent
  replicasCount: 1

  postgres:
    image: postgres:12.1-alpine
    mountPath: /var/lib/postgresql/data/
    ports: 5432
  
  cast_db:
    name: postgres-cast-db

  cast_service:
    image: superbero/cast_service:latest
    name: cast-svc-deploy

volumes:
  storageClassName: standard
  accessModes: ReadWriteMany
  
  persistentvolume:
    name: postgres-volumes
    size: 10Gi
    volume_path: /Users/admin/volumes
   
  persistentvolumeclaim:
    size: 5Gi
    storageClassName: standard
    accessModes: ReadWriteMany

    cast_db:
      name: postgres-cast-volumes-claims

services:
  postgres_cast:
    name: pg-cast
    type: ClusterIP
    port: 5432
    targetPort: 5432

  cast_service:
    type: ClusterIP
    name: cast-db-service
    port: 8000
    targetPort: 8000
